<a href="https://colab.research.google.com/github/SachinScaler/May25_Intro_to_ML_NN/blob/main/ML_Intro_to_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

url = 'https://raw.githubusercontent.com/SachinScaler/May25_Intro_to_ML_NN/refs/heads/main/cars24-car-price.csv'
df = pd.read_csv(url)
df.head()

,selling_price,year,km_driven,mileage,engine,max_power,age,make,model,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
0,1.20,2012.0,120000,19.70,796.0,46.30,11.0,MARUTI,ALTO STD,1,0,0,0,0,1,1,1,0
1,5.50,2016.0,20000,18.90,1197.0,82.00,7.0,HYUNDAI,GRAND I10 ASTA,1,0,0,0,0,1,1,1,0
2,2.15,2010.0,60000,17.00,1197.0,80.00,13.0,HYUNDAI,I20 ASTA,1,0,0,0,0,1,1,1,0
3,2.26,2012.0,37000,20.92,998.0,67.10,11.0,MARUTI,ALTO K10 2010-2014 VXI,1,0,0,0,0,1,1,1,0
4,5.70,2015.0,30000,22.77,1498.0,98.59,8.0,FORD,ECOSPORT 2015-2021 1.5 TDCI TITANIUM BSIV,0,0,1,0,0,0,1,1,0

### Tasks:

1.	Identify Non-Numerical Variables: Determine which variables in the dataset are non-numeric (categorical).

2.	Preprocess Categorical Variables:
Convert the identified non-numeric variables into suitable numerical format.

	•	What preprocessing technique would you choose?

	•	Justify your choice of technique.


3. Write an algorithm (random_picker) to pick 20 integers between the range of [1, 100] inclusive. Use the algorithm to divide the numbers into two buckets:

	•	Bucket 1: [Numbers not picked by random_picker]

	•	Bucket 2: [Numbers picked by random_picker]


4. Compute the Average Distance from the Mean: Given a list of numerical data points, calculate the average absolute distance of each point from the mean. This introduces the idea of measuring how far off data points are from a central value

```
input:
data = [2, 4, 6, 8, 10]

expected output:
2.4
```
Explanation:
- Mean of data: 6.0  
- Distances of each of the points from Mean: [4.0, 2.0, 0.0, 2.0, 4.0]  # note no negative distances
- Average Distance: 2.4